# Generated by Django 4.0.2 on 2022-04-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='sent_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
