# Generated by Django 3.0.5 on 2022-02-23 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('doctors', '0001_initial'),
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduleDate', models.DateField()),
                ('scheduleTime', models.TimeField()),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Cancel', 'Cancel'), ('Reschedule', 'Reschedule'), ('Attended', 'Attended')], max_length=10, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.Doctors')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
            ],
        ),
    ]
