# Generated by Django 3.0.5 on 2022-03-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Cancel', 'Cancel'), ('Reschedule', 'Reschedule'), ('Attended', 'Attended'), ('Pending', 'Pending')], max_length=10, null=True),
        ),
    ]
