# Generated by Django 4.0.2 on 2022-03-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_auto_20220302_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='name',
        ),
        migrations.AddField(
            model_name='prescription',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
