# Generated by Django 3.0.5 on 2022-04-01 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_auto_20220401_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
