# Generated by Django 4.0.2 on 2022-04-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='name',
        ),
        migrations.AddField(
            model_name='prescription',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
