# Generated by Django 4.0.2 on 2022-04-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_remove_schedule_scheduletime_schedule_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(blank=True, choices=[('Confirmed', 'Confirmed'), ('Cancel', 'Cancel'), ('Reschedule', 'Reschedule'), ('Attended', 'Attended'), ('Pending', 'Pending')], max_length=10, null=True),
        ),
    ]
