# Generated by Django 4.0.2 on 2022-04-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_alter_schedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='scheduleTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
