# Generated by Django 4.0.2 on 2022-04-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_schedule_scheduletime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='direction',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='remarks',
            field=models.TextField(max_length=100),
        ),
    ]
