# Generated by Django 4.0.2 on 2022-04-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_alter_prescription_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='direction',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='remarks',
            field=models.CharField(max_length=100),
        ),
    ]
