# Generated by Django 4.0.2 on 2022-04-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinfo',
            name='payment',
        ),
        migrations.AddField(
            model_name='billinfo',
            name='amount',
            field=models.PositiveIntegerField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='billinfo',
            name='balance',
            field=models.PositiveIntegerField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='billinfo',
            name='paid',
            field=models.PositiveIntegerField(max_length=200, null=True),
        ),
    ]
