# Generated by Django 4.0.3 on 2022-04-17 17:51

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0015_remove_billinfo_payment_billinfo_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='scheduleDate',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date.today), django.core.validators.MaxValueValidator(datetime.date(2022, 5, 1))]),
        ),
    ]
