# Generated by Django 4.0.3 on 2022-04-17 18:08

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0016_alter_schedule_scheduledate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='scheduleTime',
            field=models.TimeField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.time(10, 0)), django.core.validators.MaxValueValidator(datetime.time(18, 0))]),
        ),
    ]
