# Generated by Django 4.0.2 on 2022-04-18 12:32

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0017_alter_schedule_scheduletime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='scheduleDate',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date.today), django.core.validators.MaxValueValidator(datetime.date(2022, 5, 2))]),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(blank=True, choices=[('Confirmed', 'Confirmed'), ('Cancel', 'Cancel'), ('Pending', 'Pending')], max_length=10, null=True),
        ),
    ]
