# Generated by Django 4.0.2 on 2022-04-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0018_alter_schedule_scheduledate_alter_schedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='scheduleDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
