# Generated by Django 3.0.5 on 2022-02-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='role',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Staff', 'Staff')], max_length=200, null=True),
        ),
    ]
